import { getProvider } from '../ai/config.js'
import { GitScanner } from './indexer.js'
import { logger } from '../utils/logger.js'

export type DocType = 'runbook' | 'onboarding' | 'decisions'

export interface GeneratedDoc {
  type: DocType
  title: string
  content: string
  generatedAt: string
  metadata: Record<string, unknown>
}

const DOC_PROMPTS: Record<DocType, string> = {
  runbook: `Generate a comprehensive runbook for this repository based on its commit history and structure.

Include:
1. Project overview and purpose
2. Setup instructions
3. Common operations and commands
4. Troubleshooting guide
5. Architecture overview
6. Key files and their purposes

Base your documentation on the actual commit history and file structure.`,

  onboarding: `Generate an onboarding guide for new developers joining this project.

Include:
1. Welcome and project overview
2. Development environment setup
3. Codebase structure and key components
4. Development workflow (branching, PRs, testing)
5. Common tasks and how to do them
6. Who to ask for help
7. Key decisions and their rationale

Base your documentation on the actual commit history and project structure.`,

  decisions: `Extract and document key technical decisions from this repository's commit history.

Include:
1. Major architectural decisions
2. Technology choices and rationale
3. API design decisions
4. Database/schema decisions
5. Infrastructure decisions
6. Pattern and convention choices

Look for decisions in commit messages, especially those with keywords like "decide", "choose", "switch", "migrate", "refactor", "adopt".`,
}

export class DocGenerator {
  private gitScanner: GitScanner

  constructor(repoPath: string = '.') {
    this.gitScanner = new GitScanner(repoPath)
  }

  async generate(type: DocType = 'runbook'): Promise<GeneratedDoc> {
    const commits = await this.gitScanner.getCommits(undefined, 100)
    const branches = await this.gitScanner.getBranches()

    const commitSummary = commits
      .slice(0, 50)
      .map((c) => `${c.hash.substring(0, 7)} | ${c.message} | ${c.files.length} files`)
      .join('\n')

    const provider = getProvider()

    const prompt = `${DOC_PROMPTS[type]}

Repository context:
- Branches: ${branches.join(', ')}
- Total commits: ${commits.length}
- Recent commits:
${commitSummary}

Generate the documentation in markdown format.`

    const content = await provider.generateCompletion(prompt, {
      temperature: 0.5,
    })

    const titles: Record<DocType, string> = {
      runbook: 'Runbook',
      onboarding: 'Onboarding Guide',
      decisions: 'Architecture Decision Log',
    }

    const doc: GeneratedDoc = {
      type,
      title: titles[type],
      content,
      generatedAt: new Date().toISOString(),
      metadata: {
        commitCount: commits.length,
        branchCount: branches.length,
      },
    }

    logger.info(`Documentation generated: ${doc.title} (${content.length} chars)`)
    return doc
  }

  async exportMarkdown(doc: GeneratedDoc): Promise<string> {
    return `# ${doc.title}

> Generated by Spectre on ${new Date(doc.generatedAt).toLocaleDateString()}
> Based on analysis of ${doc.metadata.commitCount} commits

---

${doc.content}
`
  }
}
